=== mariya29k/Movie_Catalog/movie_catalog.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT movie_catalog (movie*)>
        <!ELEMENT movie (id, title, genre, director, rate, length, premiere, nationality, studio?, plots)>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT genre (#PCDATA)>
        <!ELEMENT director (#PCDATA)>
        <!ELEMENT rate (rating, popularity?)>
        <!ELEMENT rating (#PCDATA)>
        <!ELEMENT popularity (#PCDATA)>
        <!ELEMENT length (#PCDATA)>
        <!ELEMENT premiere (day, month, year)>
        <!ELEMENT day (#PCDATA)>
        <!ELEMENT month (#PCDATA)>
        <!ELEMENT year (#PCDATA)>
        <!ELEMENT nationality (country, language, locations?)>
        <!ELEMENT country (#PCDATA)>
        <!ELEMENT language (#PCDATA)>
        <!ELEMENT locations (#PCDATA)>
        <!ELEMENT studio (#PCDATA)>
        <!ELEMENT plots (plot+)>
        <!ELEMENT plot (plot_title, plot_author?, text)>
        <!ELEMENT plot_title (#PCDATA)>
        <!ELEMENT plot_author (#PCDATA)>
        <!ELEMENT text (#PCDATA)>

        <!ATTLIST id code ID #REQUIRED>
        <!ATTLIST director name CDATA #REQUIRED>
        <!ATTLIST day value CDATA #REQUIRED>
        <!ATTLIST month value CDATA #REQUIRED>
        <!ATTLIST year value CDATA #REQUIRED>
        <!ATTLIST studio name CDATA #REQUIRED>

=== mariya29k/Movie_Catalog/movie_1.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE movie_catalog SYSTEM "movie_catalog.dtd">
<movie_catalog>
    <movie>
        <id code="A1"></id>
        <title>Затворници</title>
        <genre>Криминален</genre>
        <director name="director">Дени Вилньов</director>
        <rate>
            <rating>8.1</rating>
            <popularity>113</popularity>
        </rate>
        <length>153</length>
        <premiere>
            <day value="day">20</day>
            <month value="month">9</month>
            <year value="year">2013</year>
        </premiere>
        <nationality>
            <country>САЩ</country>
            <language>Английски</language>
            <locations>Джорджия, САЩ</locations>
        </nationality>
        <studio name="studio">Алкън Ентъртейнмънт</studio>
        <plots>
            <plot>
                <plot_title>Разтърсващ трилър</plot_title>
                <plot_author></plot_author>
                <text>Джейк Джиленхол, Мария Бело и Хю Джакман са звездите в криминалния екшън-трилър “Затворници”,
                    който разказва за обикновения провинциален дърводелец Келър Довър (Джакман),
                    чиито живот се променя след като младата му дъщеря и нейната най-добра приятелка са отвлечени.</text>
            </plot>
        </plots>
    </movie>
</movie_catalog>

=== mariya29k/Movie_Catalog/movie_2.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE movie_catalog SYSTEM "movie_catalog.dtd">
<movie_catalog>
    <movie>
        <id code="A2"></id>
        <title>Джанго без окови</title>
        <genre>Уестърн</genre>
        <director name="director">Куентин Тарантино</director>
        <rate>
            <rating>8.4</rating>
            <popularity>180</popularity>
        </rate>
        <length>165</length>
        <premiere>
            <day value="day">25</day>
            <month value="month">12</month>
            <year value="year">2012</year>
        </premiere>
        <nationality>
            <country>САЩ</country>
            <language>Английски</language>
            <locations>Луизиана, САЩ</locations>
        </nationality>
        <studio name="studio">Юнивърсал Пикчърс</studio>
        <plots>
            <plot>
                <plot_title>Не е загуба на време</plot_title>
                <plot_author></plot_author>
                <text>Историята в ДЖАНГО БЕЗ ОКОВИ ни отвежда в северноамериканския юг две години преди
                    Гражданската война и ни запознава с роб (в изпълнение на носителя на Оскар Джейми Фокс),
                    когото съдбата среща с немския ловец на глави д-р Кинг Шулц (отличения с Оскар Кристоф Валц).
                    Шулц е по следите на братята Бритъл и само Джанго може да го отведе до тях. Шулц придобива Джанго с
                    обещанието да го освободи след залавянето на братята – живи или мъртви.</text>
            </plot>
        </plots>
    </movie>
</movie_catalog>

=== mariya29k/Movie_Catalog/movie_3.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE movie_catalog SYSTEM "movie_catalog.dtd">
<movie_catalog>
    <movie>
        <id code="A3"></id>
        <title>Маската на Зоро</title>
        <genre>Екшън</genre>
        <director name="director">Мартин Кемпбъл</director>
        <rate>
            <rating>6.8</rating>
            <popularity>1398</popularity>
        </rate>
        <length>136</length>
        <premiere>
            <day value="day">9</day>
            <month value="month">10</month>
            <year value="year">1998</year>
        </premiere>
        <nationality>
            <country>САЩ</country>
            <language>Английски</language>
            <locations>Сонора, Мексико</locations>
        </nationality>
        <studio name="studio">ТриСтар Пикчърс</studio>
        <plots>
            <plot>
                <plot_title>За истинските фенове на екшън филмите.</plot_title>
                <plot_author></plot_author>
                <text>Началото на 19 век. Дон Диего де ла Вега защитава мексиканците от провинция
                    Калифорнии от тиранията на господарите като се представя с името Зоро. По нареждане на шефа на
                    полицията без доказателства той е хвърлен зад решетките, съпругата му Есперанса е убита, а дъщеря
                    му Елена е отвлечена и отгледана от най-големия му враг Рафаел Монтеро. След 20 години Дон Диего
                    избягва от затвора. Взема под своята опека младият Алехандро, обучава го и Алехандро става
                    новият Зоро. След това той се жени за дъщерята на Дон Диего и се ражда синът им Хоакин.</text>
            </plot>
        </plots>
    </movie>
</movie_catalog>

=== mariya29k/Movie_Catalog/movie_5.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE movie_catalog SYSTEM "movie_catalog.dtd">
<movie_catalog>
    <movie>
        <id code="A5"></id>
        <title>Завръщане</title>
        <genre>Комедия</genre>
        <director name="director">Николай Илиев</director>
        <rate>
            <rating>6.9</rating>
            <popularity></popularity>
        </rate>
        <length>110</length>
        <premiere>
            <day value="day">18</day>
            <month value="month">10</month>
            <year value="year">2019</year>
        </premiere>
        <nationality>
            <country>България</country>
            <language>Български</language>
            <locations></locations>
        </nationality>
        <studio name="studio"></studio>
        <plots>
            <plot>
                <plot_title>Българското съвременно кино не е загубено.</plot_title>
                <plot_author></plot_author>
                <text>Точно 25 години след паметното футболно лято на България през 94-та,
                    трима приятели се завръщат у дома от всички краища на света, за да помогнат на друг свой приятел от
                    детството да спаси родната си къща. Алекс трябва да убеди братовчед си Бранимир да не загърбва
                    завета на дядо им, като събори фамилния им дом и построи на негово място модерна бизнес сграда.
                    Единственият начин за това е приятелите от детството да се обединят отново и да победят професионалния
                    отбор на Бранимир в градския маратон. Задачата се оказва изключително трудна,
                    а поредица от безумни случки и абсурдни препятствия поставят на изпитания дългогодишното им приятелство</text>
            </plot>
        </plots>
    </movie>
</movie_catalog>

=== mariya29k/Movie_Catalog/movie_4.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE movie_catalog SYSTEM "movie_catalog.dtd">
<movie_catalog>
    <movie>
        <id code="A4"></id>
        <title>Топло</title>
        <genre >Комедия</genre>
        <director name="director">Владимир Янчев</director>
        <rate>
            <rating>8.5</rating>
            <popularity></popularity>
        </rate>
        <length>97</length>
        <premiere>
            <day value="day">20</day>
            <month value="month">11</month>
            <year value="year">1978</year>
        </premiere>
        <nationality>
            <country>България</country>
            <language>Български</language>
            <locations>Студио Бояна, София, България</locations>
        </nationality>
        <studio name="studio">Българска кинематография</studio>
        <plots>
            <plot>
                <plot_title>За ценителите на българското кино.</plot_title>
                <plot_author></plot_author>
                <text>Хората от софийската кооперация „Цар Крум“ решават сами да си осигурят парно отопление.
                    Договарят се с трима майстори и дори им предплащат услугата. И започва голямото пробиване на дупки в стените,
                    в подове, по таваните. В един хубав ден майсторите изчезват, но дупките остават.
                    Оказва се, че тези дупки още повече ще сближат измамените и изнервени съкооператори.
                    Те са готови на всичко за да се сдобият с топлото, дори когато откриват тримата майстори в затвора.</text>
            </plot>
        </plots>
    </movie>
</movie_catalog>
